//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2Spy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int InvokeOnUIThreadActionQueueTickInterval {
            get {
                return ((int)(this["InvokeOnUIThreadActionQueueTickInterval"]));
            }
            set {
                this["InvokeOnUIThreadActionQueueTickInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopulateControlsInTreeView {
            get {
                return ((bool)(this["PopulateControlsInTreeView"]));
            }
            set {
                this["PopulateControlsInTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreserveInvalidCategoryEntriesInTreeView {
            get {
                return ((bool)(this["PreserveInvalidCategoryEntriesInTreeView"]));
            }
            set {
                this["PreserveInvalidCategoryEntriesInTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopulateServiceObjectsInTreeView {
            get {
                return ((bool)(this["PopulateServiceObjectsInTreeView"]));
            }
            set {
                this["PopulateServiceObjectsInTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopulateSmartMethodsAndPropertiesInTreeView {
            get {
                return ((bool)(this["PopulateSmartMethodsAndPropertiesInTreeView"]));
            }
            set {
                this["PopulateSmartMethodsAndPropertiesInTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopulateControlsInUsesAnalysis {
            get {
                return ((bool)(this["PopulateControlsInUsesAnalysis"]));
            }
            set {
                this["PopulateControlsInUsesAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreExceptionsInGetUsesInformationAsync {
            get {
                return ((bool)(this["IgnoreExceptionsInGetUsesInformationAsync"]));
            }
            set {
                this["IgnoreExceptionsInGetUsesInformationAsync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopulateSmartMethodsAndPropertiesInUsesAnalysis {
            get {
                return ((bool)(this["PopulateSmartMethodsAndPropertiesInUsesAnalysis"]));
            }
            set {
                this["PopulateSmartMethodsAndPropertiesInUsesAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeepXPathDocumentsInMemory {
            get {
                return ((bool)(this["KeepXPathDocumentsInMemory"]));
            }
            set {
                this["KeepXPathDocumentsInMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ConnectionCachePingFrequencyInMiliseconds {
            get {
                return ((int)(this["ConnectionCachePingFrequencyInMiliseconds"]));
            }
            set {
                this["ConnectionCachePingFrequencyInMiliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtractFormattedDefinitions {
            get {
                return ((bool)(this["ExtractFormattedDefinitions"]));
            }
            set {
                this["ExtractFormattedDefinitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopulateWorkflowsInTreeView {
            get {
                return ((bool)(this["PopulateWorkflowsInTreeView"]));
            }
            set {
                this["PopulateWorkflowsInTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExperimentalDelayedInitializationOfTreeView {
            get {
                return ((bool)(this["ExperimentalDelayedInitializationOfTreeView"]));
            }
            set {
                this["ExperimentalDelayedInitializationOfTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server|Database\r\nsqlconnection\r\nassembly full name\r\nservice endpoint url\r\nwebserv" +
            "ice url\r\ndescriptor location")]
        public string ExternalServiceInstanceResourcesProperties {
            get {
                return ((string)(this["ExternalServiceInstanceResourcesProperties"]));
            }
            set {
                this["ExternalServiceInstanceResourcesProperties"] = value;
            }
        }
    }
}
